"""posts table

Revision ID: 557d046d15e4
Revises: 674e05624f75
Create Date: 2019-07-16 23:42:34.252885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557d046d15e4'
down_revision = '674e05624f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('my_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.my_id'], ),
    sa.PrimaryKeyConstraint('my_id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###
